env: production # to enable google analytics, opengraph, twitter-cards and schema.
title: Erfan Alimohammadi
description: Software Engineer and Data Scientist
author: Erfan Alimohammadi

rssFullContent: true

images:
  - images/avatar.jpg

ShowReadingTime: true
ShowShareButtons: true
comments: true
defaultTheme: auto
disableSpecial1stPost: true

homeInfoParams:
  Title: Erfan Alimohammadi
  Content: Software Engineer and Data Scientist

socialIcons:
  - name: twitter
    url: https://twitter.com/erfanafre
  - name: stackoverflow
    url: https://stackoverflow.com/users/2635857/erfan-alimohammadi
  - name: github
    url: https://github.com/erfaniaa
  - name: linkedin
    url: https://www.linkedin.com/in/erfan-alimohammadi
  - name: email
    url: mailto:erfan.aa@gmail.com
