title: مهدی خوشنودی
description: پر شور و شوق در مورد معماری نرم‌افزار، راهبری و استارتاپ‌ها.
author: مهدی خوشنودی
homeInfoParams:
  Title: مهدی خوشنودی
  Content: پر شور و شوق در مورد معماری نرم‌افزار، راهبری و استارتاپ‌ها.
