baseURL: https://mehdy.me/
title: Mehdy Khoshnoody
defaultContentLanguage: en-us
languageCode: en-us
languageName: English

theme: PaperMod

paginate: 20

googleAnalytics: UA-171541179-1

enableRobotsTXT: true

disqusShortname: mehdy

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: /posts/:year/:month/:slug/

taxonomies:
  tag: tags
  archive: archives

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mehdy Khoshnoody
  description: Passionate about software architecture, startups and leadership.
  author: Mehdy Khoshnoody

  rssFullContent: true

  images: 
    - images/avatar.jpg

  ShowReadingTime: true
  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableSpecial1stPost : false

  profileMode:
    enabled: false
    title: Mehdy Khoshnoody
    imageUrl: images/avatar.jpg
    imageTitle: Mehdy Khoshnoody
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: Mehdy Khoshnoody
    Content: Passionate about software architecture, startups and leadership.

  socialIcons:
    - name: twitter
      url: https://twitter.com/mehdy314
    - name: stackoverflow
      url: https://stackoverflow.com/users/3654352/mehdy
    - name: github
      url: https://github.com/mehdy
    - name: linkedin
      url: https://www.linkedin.com/in/mehdy314
    - name: email
      url: mailto:mehdy.khoshnoody+blog@gmail.com

menu:
  main:
    - weight: 1
      identifier: home
      name: Home
      url: /
    - weight: 2
      identifier: tags
      name: Tags
      url: /tags
    - weight: 3
      identifier: archives
      name: Archives
      url: /archives
